### PR TITLE
Prefix Sum code added

### PR DESCRIPTION
**Pull request by Radhey644**
## Description
A prefix sum is a method to quickly calculate the sum of elements in an array up to a given index. It simplifies range queries and cumulative operations by maintaining a running sum in a separate array. This optimization technique is essential for efficient sum calculations in algorithms.

## Screenshots 
image
image

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by himanshu-03 — COMMENTED** [review]
Hey sorry but we arent accepting c/c++ codes here.

**Comment by Radhey644** [comment]
I am so sorry sir,
I am giving you It is the python format instead.

**Comment by Radhey644** [comment]
image
The Work Is Upgraded

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
I guess this should be coming under the Math directory and not the Array directory

**Comment by Radhey644** [comment]
Work Done!!

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
