### PR TITLE
Create Bucket_Sort.py #25

### PR DESCRIPTION
**Pull request by Astha369**
Please review under hacktoberfest label. Thank you!

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Great job there. It would be great if the code can accept dynamic input

**Comment by Astha369** [comment]
I made the suggested changes, kindly review them!

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
