### PR TITLE
algo: merge sort

### PR DESCRIPTION
**Pull request by ashishk1331**
## Title :
Added algorithm to perform merge sort on an array.

## Description
Added file `Merge_Sort.py` inside the folder `Algorithms/Sorting Techniques` with relevant code and comments describing merge sort in brief.

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by ashishk1331** [comment]
Okay, no problem. I'll just create an issue then link it here.

**Comment by himanshu-03** [comment]
> Okay, no problem. I'll just create an issue then link it here.

Hey @ashishk1331 ! When are you planning to create the issue?

**Comment by ashishk1331** [comment]
I'll do it right now.

**Comment by ashishk1331** [comment]
Closes #33

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Comment by ashishk1331** [comment]
Thank you for accepting the PR. Actually my tight college schedule had me, that's the reason why I wasn't able to file an issue before. 🙃

**Pull request merged**
