### PR TITLE
Algo: Pattern Searching Algorithm, Naive Pattern Searching

### PR DESCRIPTION
**Pull request by ConradKash**
## Title :

Added Naive Pattern Searching
## Issue no : 

#80 

## Description

Naive pattern searching is the simplest method among other pattern-searching algorithms. It checks for all characters of the main string to the pattern. This algorithm is helpful for smaller texts. It does not need any pre-processing phases.
I can find the substring by checking once for the string. It also does not occupy extra space to perform the operation.

The time complexity of Naive Pattern Search method is O(m*n). The m is the size of pattern and n is the size of the main string.

I have added an option for one to enter there desired text and character to try it out themselves

## Screenshots (if applicable)

image

## Checklist
- [yes] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [yes] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
I suggest removing the static code and example fullly and if not atleast make a proper seperation between them, it would be great if the static input is also displayed in the output in this case.

**Comment by statst** [comment]
> I suggest removing the static code and example fullly and if not atleast make a proper seperation between them, it would be great if the static input is also displayed in the output in this case.

Done

**Comment by ConradKash** [comment]
> I suggest removing the static code and example fullly and if not atleast make a proper seperation between them, it would be great if the static input is also displayed in the output in this case.

image
I have worked on it

**Review by himanshu-03 — APPROVED** [review]
Lgtm!

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Ig it should come under searching techniques folder.

**Comment by ConradKash** [comment]
> Ig it should come under searching techniques folder.

Done

**Review by himanshu-03 — APPROVED** [review]
Lgtm!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
