### PR TITLE
Fibonacci Searching Algorithm 

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
## Description

- Added `.py` file of fibonacci searching algorithm with named `Fibonacci_Searching.py`
## Screenshots (if applicable)

image

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@himanshu-03 please review this pull request and requested to merge it under hacktoberfest 2023

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Try to keep the input dynamic

**Comment by Avdhesh-Varshney** [comment]
> Try to keep the input dynamic

@himanshu-03 please again review this pull request. I have done with the changes and makes the code to the dynamic input from the user.

**Comment by himanshu-03** [comment]
Hi @Avdhesh-Varshney !

There has been a slight change in our directory structure! Can you please sync the changes from main branch?

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
