### PR TITLE
Add traveling salesman algorithm

### PR DESCRIPTION
**Pull request by AaryaNale**
## Description
Added python code for the traveling salesman algorithm along with a README file

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by AaryaNale** [comment]
I forked the repo and added some sorting algorithms here first, due to the confusion i mentioned in issue #49 
I have removed/deleted those files and now the new fork only contains files related to traveling salesman algorithm.
Please let me know if i need to change something.
Thanks.

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
hey @AaryaNale !

There are folders for specific data structure, I suggest adding this in the desired category!
You dont need to add any specific readme for your project.

**Comment by AaryaNale** [comment]
image
None of these categories seem like they can fit in this code. Please help me with which folder to add this algo in.

**Comment by AaryaNale** [comment]
I've done the changes. Please review.

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Thank you for contributing ✨️🚀
Do give this repostory a star ⭐️ if you feel like.

**Pull request merged**
