### PR TITLE
Create Kruskals_Algorithm.py

### PR DESCRIPTION
**Pull request by AaryaNale**
## Title :
Kruskal's algorithm

## Issue no : 
Solves #74 

## Description
Kruskal's algorithm is a minimum spanning tree algorithm that finds the smallest set of edges that connects all vertices in a graph without forming cycles. Adding this to the "Graphs" folder.

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
It would be great if the Program could accept dynamic input from user.

**Comment by AaryaNale** [comment]
Please review and suggest changes.
Thanks.

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
