### PR TITLE
algo/code: 1) Added BFS traversal in graph and Topological sort for DAG

### PR DESCRIPTION
**Pull request by preyalameta02**
## Title :
Added BFS Traversal Technique for Graph and Topological sort for Directed Acyclic Graph using Recursion

## Issue no : 
#36

## Description
Added Topological_Sort.py in Sorting and bfs.py in Graphs

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Great work there @preyalameta02 !
It would be great if the codes that you provided could accept a dynamic user input.

**Comment by preyalameta02** [comment]
Latest code accepts dynamic user input.

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Comment by preyalameta02** [comment]
Hey Himanshu, can you please add a hactoberfest-accepted label to this PR.

**Pull request merged**
