### PR TITLE
Create Exponetialsearch.py

### PR DESCRIPTION
**Pull request by s7917**
## Title : 
Exponential sorted alogorithms

## Description
i have added the extponential seach code in python language which are not added by anyone

## Checklist
- [ ] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by s7917** [comment]
this is the code of exponential search in python. this code is not  present in the repository so i contribute this for your repo.
if this good is better for your repository then merge it

**Comment by himanshu-03** [comment]
> ## Title :
> ## Issue no :
> ## Description
> ## Screenshots (if applicable)
> ## Checklist
> * [x]  I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  I have read and followed the **Contributing Guidelines**

Hey @s7917 !
Great job there on implementing Exponential Search. However it would be great if you can follow the COC and update the details in your PR here

**Comment by himanshu-03** [comment]
> Screenshot 2023-10-11 120710 @himanshu-03 please see that screenshot.... this interface is show in my repository.... resolve this issue please

yes this is fine it would be great if you can update the details in your PR here
image

**Comment by s7917** [comment]
i am creating poll request again for exponential search 
and now i am close this poll request...............

**Pull request closed without merging**
