### PR TITLE
added gbfs and astar search algorithms

### PR DESCRIPTION
**Pull request by Kallind**
added gbfs and astar search algorithms using manhattan as the heuritstic function. Created a folder called graph for the same

## Description 
Added GBFS and Astar search algorithm for graphs using Manhattan as the heuristic function

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Comment by himanshu-03** [comment]
Hey @Kallind !

It would be great if you can follow the Contributing Guidelines mentioned in the repo. You can first create an issue and link your PR over there. Happy Hacking! Also, do let me know if you need any help.

**Comment by Kallind** [comment]
hey i have made the issue can you help me with linking this PR to the issue

**Comment by Kallind** [comment]
@himanshu-03 added the dynamic functionality as requested also added the details of the PR. Please review it. Thank you

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
