### PR TITLE
Added Cycle Sort Technique

### PR DESCRIPTION
**Pull request by Villain45**
Added Cycle Sort Technique #20

### CODE REVIEW

**Review by himanshu-03 — CHANGES_REQUESTED** [review]
Great job there! I was thinking if we can have a dynamic input in the code, that would be much better

**Comment by Villain45** [comment]
requested changes are done

**Review by Villain45 — COMMENTED** [review]
requested changes are done

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
