### PR TITLE
Update README.md (a16b8a2) issue resolved

### PR DESCRIPTION
**Pull request by Khushi-Gupta13**
made some changes in the description

### CODE REVIEW

**Comment by himanshu-03** [comment]
Hello @Khushi-Gupta13 !

Open an issue first and then link it here in the description.
Please follow the Contributing Guidelines you need to fill all the PR details which was mentioned.

**Comment by Khushi-Gupta13** [comment]
#35 Enhancement of Readme.md file issue resolved.

**Review by himanshu-03 — APPROVED** [review]
LGTM!

**Comment by himanshu-03** [comment]
Great job!
Thank you for contributing. Do give this repository a star if you feel like ✨️

**Pull request merged**
